def glInit() -> None:
    ...

def clearBuffer(r: float = 0.0, g: float = 0.0, b: float = 0.0, a: float = 0.0) -> None:
    ...

class Atlas:
    
    def __init__(self, path: str): ...

class SkeletonJson:
    def __init__(self, atlas: Atlas): ...

    def readSkeletonDataFile(self, path: str) -> SkeletonData: ...

class Skin: ...

class SkeletonData:

    def findSkin(self, skeletonData: SkeletonData) -> Skin: ...

class AnimationStateData: ...

class Skeleton:

    def __init__(self, skeletonData: SkeletonData, animationStateData: AnimationStateData):
        self.usePremultipliedAlpha: bool = ...
        self.x: float = ...
        self.y: float = ...
        self.canvasWidth: int = ...
        self.canvasHeight: int = ...
    
    def update(self, deltaTime: float) -> None: ...
    
    def draw(self) -> None: ...
    
    def setSkin(self, skin: Skin) -> None: ...

    def setToSetupPose(self) -> None: ...

    def addAnimationByName(self, trackIndex: int, name: str, loop: bool, delay: float): ...

    def setAnimationByName(self, trackIndex: int, name: str, loop: bool): ...



